name: Ejemplo de GitHub Actions  # Nombre de la acción

on: push  # Evento que desencadena la ejecución de la acción (en este caso, un push)

jobs:  # Definición de los trabajos a realizar
  build:  # Nombre del trabajo
    runs-on: ubuntu-latest  # Sistema operativo en el que se ejecutará el trabajo

    steps:  # Definición de los pasos individuales dentro del trabajo
      - name: Paso 1  # Nombre del paso
        run: echo "Este es el paso 1"  # Comando a ejecutar en el paso

      - name: Paso 2  # Nombre del paso
        run: echo "Este es el paso 2"  # Comando a ejecutar en el paso

        if: github.event_name == 'push'  # Condición para ejecutar el paso solo en caso de un push

      - name: Paso 3  # Nombre del paso
        run: echo "Este es el paso 3"  # Comando a ejecutar en el paso

        #needs: [build]  # Especifica que este paso necesita que el trabajo "build" se complete antes de ejecutarse
